create  table if not exists src.user_account(
  id int comment '',
  type string comment '',
  username string comment '',
  nickname string comment '',
  auth_key string comment '',
  password_hash string comment '',
  password_reset_token string comment '',
  email string comment '',
  status int comment '',
  head string comment '',
  created_at int comment '',
  updated_at int comment '',
  role int comment '',
  day_user int comment '',
  no_buy int comment '',
  telephone_system_name string comment '',
  telephone_system_pwd string comment '',
  crm_chat_uuid string comment '',
  card string comment '',
  poster string comment '',
  qrcode string comment '',
  banner string comment '员工banner图',
  is_test int comment '',
  channel_code string comment '',
  department int comment '',
  month_target int comment '',
  teacher_role int comment '1：社招培训师，2：校招培训师，3：社招管理员，4：校招管理员，5：监察，6：教研客服，7：销售客服，8：运营，9：总管理员',
  update_time int comment '更新时间',
  employee_type int comment '员工类型 0：技术，1：销售',
  important_count int comment '客服当前重要用户数量',
  phone string comment '手机号码',
  department_id bigint comment '部门ID',
  is_leader int comment '0-普通成员, 1-部门领导',
  ex_push_flag int comment '体验课后未回访推送判断字段 0-默认推送, 1-优秀新签无需推送',
  tms_chat_uuid string comment 'tms聊天系统的uuid'
)
comment =''
;
