create  table if not exists src.user_teacher(
  id int comment '',
  mobile string comment '',
  password string comment '',
  role int comment '',
  nick string comment '',
  show_name string comment '',
  gender int comment '',
  teacher_level int comment '老师等级(算钱)',
  head_icon string comment '',
  place_id int comment '',
  work_type int comment '老师工作类型(2018-08-01开始启用)  -1: 未选择  1:全职老师  2:兼职老师 ',
  teacher_group int comment '',
  position int comment '',
  image_available int comment '',
  ex int comment '',
  pay int comment '',
  ex_to_pay double comment '',
  logout_time int comment '',
  time_created int comment '',
  time_updated int comment '',
  is_disabled int comment '',
  class_hour_first double comment '',
  class_hour_second double comment '',
  class_hour_third double comment '',
  resume string comment '',
  is_firstLogin int comment '',
  accessToken string comment '',
  chat_token string comment '',
  is_formal int comment '',
  employedtime int comment '',
  is_test int comment '',
  version string comment '',
  work_id int comment '工作状态（新）1:待培训(废弃) 2:待入职 3:在职 4:离职 5:待审核(通过teacher_type区分社招校招 ,目前teacher_type=2的为培训) 6:社招注册待分配 7:备用人才 8：面试',
  type int comment '',
  teacher_type int comment '',
  school_id int comment '',
  salary_rate int comment '',
  open_id string comment '',
  style int comment '',
  sounds int comment '',
  teacher_experience int comment '',
  responsible_school string comment '',
  email string comment '',
  birthday int comment '',
  id_number string comment '',
  address string comment '',
  is_graduated int comment '',
  teacher_master int comment '',
  justalk_open_private int comment 'justalk私有开关，0表示关闭，1表示开启',
  yunxin_open_private int comment 'yunxin私有开关，0表示关闭，1表示开启',
  major string comment '专业',
  graduate_school string comment '毕业院校',
  departure_time int comment '离职时间',
  performance_level int comment '演奏级别 1一级 2 二级 3 三级 4 四级 5 五级 6 六级 7 七级 8 八级 9 究极 10 十级 11 演奏级',
  fixtime_apply_status int comment '老师固定时间申请状态，0：不在申请中，1：在申请中',
  course_lock int comment '安排课程约束添加',
  time_locked int comment '课程锁获取添加时间',
  language string comment '语言能力',
  update_time string comment '更新时间',
  chat_uuid string comment 'tms聊天系统的uuid'
)
comment =''
;
