create table src.src_users(
    id  bigint,
    first_id    string,
    second_id   string,
    user_life_Cycle string,
    register_source string,
    phone   string,
    register_date_time  bigint,
    register_channel    string ,
    first_visit_source  string ,
    first_visit_channel string ,
    first_visit_time    bigint ,
    first_referrer  string ,
    first_browser_language string ,
    first_browser_charset   string ,
    first_referrer_host    string ,
    first_traffic_source_type   string ,
    first_search_keyword   string ,
    utm_source  string ,
    utm_medium string ,
    utm_campaign    string ,
    utm_content string ,
    utm_term   string,
    first_visit_os  string ,
    first_visit_scene   double ,
    zhuanyizhuceyonghu  string ,
    fenqun3 string ,
    fenqun31    string ,
    yichangfangwenxiaochengxu   string ,
    h10aVisitors    string ,
    FakeVisitors    string ,
    guangdiantongyonghu string ,
    jinritoutiaoyonghu  string ,
    baiduyonghu string ,
    weixinpengyouquanyonghu string ,
    sms_lost    string ,
    sms_lost2   string ,
    tiaoqirenjiyanzhengshibai   string ,
    sms_fail_0730   string ,
    tyceshishipin_and   string ,
    sms_lost_detail string ,
    yuetoutiaoanzhuo    string
)partitioned by(year STRING, month STRING,day string) row format delimited fields terminated by '\001'
;